export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const CREATE_APARTMENT_SUCCESS = "CREATE_APARTMENT_SUCCESS";
export const CREATE_APARTMENT_FAIL = "CREATE_APARTMENT_FAIL";
export const APARTMENT_SELECTED_FILE = "APARTMENT_SELECTED_FILE";

export const FETCH_APARTMENT_PENDING = "FETCH_APARTMENT_PENDING";
export const FETCH_APARTMENT_SUCCESS = "FETCH_APARTMENT_SUCCESS";
export const FETCH_APARTMENT_FAIL = "FETCH_APARTMENT_FAIL";

export const DELETE_APARTMENT_PENDING = "DELETE_APARTMENT_PENDING";
export const DELETE_APARTMENT_SUCCESS = "DELETE_APARTMENT_SUCCESS";
export const DELETE_APARTMENT_FAIL = "DELETE_APARTMENT_FAIL";